package com.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileMark<M extends BaseFileMark<M>> extends Model<M> implements IBean {

	public void setFileId(java.lang.String fileId) {
		set("file_id", fileId);
	}

	public java.lang.String getFileId() {
		return get("file_id");
	}

	public void setIsCut(java.lang.Boolean isCut) {
		set("is_cut", isCut);
	}

	public java.lang.Boolean getIsCut() {
		return get("is_cut");
	}

}
