package com.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWholeChunkMapping<M extends BaseWholeChunkMapping<M>> extends Model<M> implements IBean {

	public void setChunkMd5(java.lang.String chunkMd5) {
		set("chunk_md5", chunkMd5);
	}

	public java.lang.String getChunkMd5() {
		return get("chunk_md5");
	}

	public void setWholeMd5(java.lang.String wholeMd5) {
		set("whole_md5", wholeMd5);
	}

	public java.lang.String getWholeMd5() {
		return get("whole_md5");
	}

	public void setIsUpload(java.lang.String isUpload) {
		set("is_upload", isUpload);
	}

	public java.lang.String getIsUpload() {
		return get("is_upload");
	}

	public void setSerial(java.lang.Integer serial) {
		set("serial", serial);
	}

	public java.lang.Integer getSerial() {
		return get("serial");
	}

}
