package com.xgs.net.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFileUpload<M extends BaseFileUpload<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setWholeMd5(java.lang.String wholeMd5) {
		set("whole_md5", wholeMd5);
	}

	public java.lang.String getWholeMd5() {
		return get("whole_md5");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

	public void setFileExt(java.lang.String fileExt) {
		set("file_ext", fileExt);
	}

	public java.lang.String getFileExt() {
		return get("file_ext");
	}

	public void setMimeType(java.lang.String mimeType) {
		set("mime_type", mimeType);
	}

	public java.lang.String getMimeType() {
		return get("mime_type");
	}

	public void setSize(java.lang.Long size) {
		set("size", size);
	}

	public java.lang.Long getSize() {
		return get("size");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

}
