package com.xgs.net.model;

import com.xgs.net.model.base.BaseChunkFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChunkFile extends BaseChunkFile<ChunkFile> {
	public static final ChunkFile dao = new ChunkFile().dao();
}
