package com.xgs.net.model;

import com.xgs.net.model.base.BaseFileUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileUpload extends BaseFileUpload<FileUpload> {
	public static final FileUpload dao = new FileUpload().dao();
}
