package com.xgs.net.model;

import com.xgs.net.model.base.BaseFileMark;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FileMark extends BaseFileMark<FileMark> {
	public static final FileMark dao = new FileMark().dao();
}
