package com.xgs.net.model;

import java.util.Map;

import java.util.HashMap;

import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
public class TableKit {

	private static Map<String,Class<? extends Model<?>>> map = new HashMap<String,Class<? extends Model<?>>>();

	public static Map<String,Class<? extends Model<?>>> mapping() {
		return map;
	}

	static{
		map.put("chunk_file", ChunkFile.class);
		map.put("file_mark", FileMark.class);
		map.put("file_upload", FileUpload.class);
		map.put("upload_whole_file", UploadWholeFile.class);
		map.put("whole_chunk_mapping", WholeChunkMapping.class);
		map.put("whole_file", WholeFile.class);
	}
}

