package com.xgs.net.model;

import com.xgs.net.model.base.BaseUploadWholeFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadWholeFile extends BaseUploadWholeFile<UploadWholeFile> {
	public static final UploadWholeFile dao = new UploadWholeFile().dao();
}
