package com.xgs.net.model;

import com.xgs.net.model.base.BaseWholeChunkMapping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WholeChunkMapping extends BaseWholeChunkMapping<WholeChunkMapping> {
	public static final WholeChunkMapping dao = new WholeChunkMapping().dao();
}
