package com.xgs.net.model;

import com.xgs.net.model.base.BaseWholeFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WholeFile extends BaseWholeFile<WholeFile> {
	public static final WholeFile dao = new WholeFile().dao();
}
